#!/usr/bin/python3

import argparse
import atexit
from glob import glob
import os
import subprocess
import sys
import tempfile
import time

# FIXME use stat / and Check "Device" output
def find_root_dev():
    df = subprocess.check_output(["df","/"], universal_newlines=True)
    for line in df.split("\n"):
        if line.startswith("/"):
            return line.split()[0][:-1]

    return "/dev/vda"

def find_esp_mount():
    return "/boot/efi"

def unmount(path):
    subprocess.call(["umount", "-l", path])

def disconnect_nbd(blockdev, temp_dir):
    subprocess.call(["qemu-nbd", "-d", blockdev], stdout=subprocess.DEVNULL)
    subprocess.call(["rm", "-rf", temp_dir])
    subprocess.call(["rmmod", "nbd"])

def parse_fdisk(fdisk_output):
    result = {}
    for line in fdisk_output.split("\n"):

        if not line.startswith("/"): continue
        parts = line.split()

        inf = {}
        inf['part_type_guid'] = parts[1]

        result[parts[0]] = inf
    return result

def print_fail(testname):
    print("%s: FAIL"  % testname)

def print_pass(testname):
    print("%s: PASS"  % testname)

def print_result(testname, result):
    if result:
        print("%s: PASS"  % testname)
    else:
        print("%s: FAIL"  % testname)

def check_hw_description():
    print_result("VMSPEC-EFI", os.path.isfile("/sys/firmware/efi/systab"))
    print_result("VMSPEC-EFI-DTB", os.path.isfile("/sys/firmware/fdt"))
    has_acpi = False
    with open('/sys/firmware/efi/systab') as acpi:
        for line in acpi:
            if line.startswith("ACPI20"):
                has_acpi = True

    print_result("VMSPEC-EFI-ACPI", has_acpi)

def print_fail(testname):
    print("%s: FAIL"  % testname)

def check_sbsa_console():
    has_sbsa_uart = False
    with open('/proc/tty/driver/ttyAMA') as sbsa_uart:
        for line in sbsa_uart:
            if line.startswith("serinfo:"): continue
            parts = line.split()
            if parts[2]=="SBSA":
                has_sbsa_uart = True
    print_result("VMSPEC-OS-SBSA-UART", sbsa_uart)

def main():
    parser = argparse.ArgumentParser(description="VMSPEC validation suite")
    parser.add_argument("-i","--image", help="Image to test")
    arguments = parser.parse_args()

    image=arguments.image
    #  sudo modprobe nbd max_part=16
    if image is not None:
        blockdev = "/dev/nbd0"
        test_dir = tempfile.mkdtemp("vmspec")
        try:
            subprocess.call(["modprobe", "nbd", "max_part=16"])
        except:
            print("ERROR: \"modprobe nbd\" failed, are your root?")
            return 1
        time.sleep(2)
        subprocess.call(["qemu-nbd", image, "-c",blockdev])
        atexit.register(disconnect_nbd, blockdev, test_dir)
    else:
        blockdev = find_root_dev()
        test_dir = find_esp_mount()

    try:
        fdisk_output = subprocess.check_output(["fdisk","-l",blockdev,"-o","Device,Type-UUID"],
                universal_newlines=True)
    except:
        print_fail("VMSPEC-IMAGE-GPT")
        return 1
    print_pass("VMSPEC-IMAGE-GPT")

    test_disk="/dev/null"
    has_esp = False
    for disk, info in parse_fdisk(fdisk_output).items():
        if info['part_type_guid'] == "C12A7328-F81F-11D2-BA4B-00A0C93EC93B":
            has_esp = True
            test_disk = disk
    #    print([disk, " ".join(["%s=%r" % i for i in info.items()])])
    print_result("VMSPEC-IMAGE-ESP", has_esp)
    if image is not None:
        subprocess.call(["partprobe", blockdev])
        subprocess.call(["mount", "-t", "vfat", test_disk, test_dir])
        atexit.register(unmount, test_dir)
    try:
        file_output = subprocess.check_output(("file -b %s/EFI/BOOT/BOOTAA64.EFI" % test_dir ),
                universal_newlines=True, shell=True)
    except:
        print_fail("VMSPEC-IMAGE-BOOTAA64")
        return 1
    has_bootaa64 = file_output.startswith('PE32+ executable (EFI application)')
    print_result("VMSPEC-IMAGE-BOOTAA64", has_bootaa64 )

    if image is not None:
        print("skipping runtime tests")
        return 0

    check_hw_description()
    print_result("VMSPEC-OS-EFI", os.path.isdir("/sys/firmware/efi"))

    has_efi_rtc=False
    for rtc in glob("/sys/class/rtc/rtc*"):
        if os.path.realpath(rtc).startswith("/sys/devices/platform/rtc-efi/rtc/rtc0"):
            has_efi_rtc=True
    print_result("VMSPEC-OS-EFI-RTC", has_efi_rtc)
    print_result("VMSPEC-OS-ACPI", os.path.isdir("/sys/firmware/acpi"))
    check_sbsa_console()

if __name__ == '__main__': main()
